<a href="https://colab.research.google.com/github/Asmaaad37/Machine-Learning/blob/main/Olympics-EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
bios = pd.read_csv('bios.csv')

In [ ]:
bios.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2.0,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3.0,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4.0,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5.0,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# What should we clean ?
# Get Rid of bullet points in Used Names [Done]
# Get Rid of Extra Columns [Done]
# Split Height/Weight [Done]
# Parse Out dates from 'Born' and 'Died' column [Done]
# Parese Out city, region and country from 'Born' column [Done]

In [ ]:
# Making the copy of the original data
df = bios.copy()

In [ ]:
df['name'] = df['Used name'].str.replace("•", " ")
# df.drop('Name', axis=1, inplace=True)

In [ ]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2.0,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3.0,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4.0,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5.0,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet

In [ ]:
# Splitting Height / Weight
# df.drop(columns=['height', 'weight'], inplace=True)
df[['height_cm', 'weight_kg']] = df['Measurements'].str.split('/', expand=True)

In [ ]:
# Check to make sure values have the '/'.
df[~df['Measurements'].str.contains('/', na=False) & df['Measurements'].notna()]
# small_data = pd.DataFrame(['183 cm', '180 cm / 150 kg', '190 cm / 80 kg', '100 kg'], columns = ["Measurements"])
# small_data[['height_cm', 'weight_kg']] = small_data['Measurements'].str.split('/', expand=True)
# small_data['weight_kg'].fillna(small_data['height_cm'], inplace=True)

# small_data['height_cm'] = pd.to_numeric(small_data['height_cm'].str.strip(' cm'), errors='coerce')
# small_data['weight_kg'] = pd.to_numeric(small_data['weight_kg'].str.strip(' kg'), errors='coerce')

# small_data.head()

# Get Rid of 'cm' and 'kg' from our new column

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
87,Competed in Olympic Games • Non-starter,Male,"Hugh Lawrence ""Laurie""•Doherty",Laurie•Doherty,"8 October 1875 in Wimbledon, England (GBR)","21 August 1919 in Broadstairs, England (GBR)",Great Britain,88.0,178 cm,"All England Lawn Tennis and Croquet Club, Wimb...",Little Do,NaN,NaN,NaN,NaN,NaN,Laurie Doherty,178 cm,None
105,Competed in Olympic Games,Male,Harold Segerson•Mahony,Harold•Mahony,"13 February 1867 in Edinburgh, Scotland (GBR)","27 June 1905 in between Glencar and Killorgin,...",Great Britain,106.0,191 cm,"Fitzwilliam Lawn Tennis Club, Dublin (IRL)",NaN,NaN,NaN,Ireland,NaN,NaN,Harold Mahony,191 cm,None
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia•Offel,19 December 1971,NaN,Ghana,166.0,120 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patricia Offel,120 kg,None
242,Competed in Olympic Games,Female,"Lucia Francisca ""Susy""•Susanti Haditono",Susy•Susanti,"11 February 1971 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,243.0,161 cm,"Jaya Raya, Jakarta (INA)",NaN,NaN,"Wang Lianxiang, 王蓮香",NaN,NaN,NaN,Susy Susanti,161 cm,None
243,Competed in Olympic Games,Female,Lili•Tampi,Lili•Tampi,"19 May 1970 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,244.0,161 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lili Tampi,161 cm,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21999,Competed in Olympic Games,Male,Cecil Ashworth•Kershaw,Cecil•Kershaw,"3 February 1895 in Dhaka (Dacca), Dhaka (BAN)","1 November 1972 in Worthing, England (GBR)",Great Britain,22158.0,173 cm,Royal Navy School of Physical Training,K,NaN,NaN,NaN,NaN,NaN,Cecil Kershaw,173 cm,None
22007,Competed in Olympic Games,Male,Alfred Ridley•Martin (-Ridley-Martin),Alfred•Ridley-Martin,"9 May 1881 in Lewisham, England (GBR)","6 May 1970 in Purley, England (GBR)",Great Britain,22166.0,188 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alfred Ridley-Martin,188 cm,None
22046,Competed in Olympic Games • Referee,Male,Thomas Harrison•Wand-Tetley,Thomas•Wand-Tetley,"26 September 1890 in Paignton, England (GBR)","4 February 1956 in Saint Mary, Jersey (JER)",Great Britain,22205.0,175 cm,The Wiltshire Regiment,NaN,NaN,NaN,NaN,NaN,NaN,Thomas Wand-Tetley,175 cm,None
22050,Competed in Olympic Games • Referee,Male,Roland Moffatt Perowne•Willoughby,Roland•Willoughby,"6 September 1870 in Marylebone, England (GBR)","15 February 1954 in Chelsea, England (GBR)",Great Britain,22210.0,178 cm,"London Fencing Club, London (GBR)",NaN,NaN,NaN,NaN,NaN,NaN,Roland Willoughby,178 cm,None
22090,Competed in Olympic Games • Referee,Male,Bernhard Artur Erwin•Casmir,Erwin•Casmir,"2 December 1895 in Spandau, Berlin (GER)","19 April 1982 in Frankfurt am Main, Hessen (GER)",Germany,22251.0,180 cm,"FC Hermannia, Frankfurt am Main (GER)",NaN,NaN,NaN,West Germany,NaN,NaN,Erwin Casmir,180 cm,None

In [ ]:
# small_data['height_cm'] = pd.to_numeric(small_data['height_cm'].str.strip(' cm'), errors='coerce')
# small_data.head()

      Measurements  height_cm weight_kg
0           183 cm      183.0      None
1  180 cm / 150 kg      180.0    150 kg
2   190 cm / 80 kg      190.0     80 kg
3           100 kg        NaN      None

In [ ]:
# Get rid of " cm" and the " kg" from our new columns
df['height_cm'] = pd.to_numeric(df['height_cm'].str.strip(' cm'), errors='coerce')
df['weight_kg'] = pd.to_numeric(df['weight_kg'].str.strip(' kg'), errors='coerce')

In [ ]:
# Sorting Values
df.sort_values('height_cm', ascending = False)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
5781,Competed in Olympic Games,Male,"Thomas Loren ""Tommy""•Burleson",Tommy•Burleson,"24 February 1952 in Crossnore, North Carolina ...",NaN,United States,5804.0,223 cm / 102 kg,"NC State Wolfpack, Raleigh (USA)",NaN,NaN,NaN,NaN,NaN,NaN,Tommy Burleson,223.0,102.0
6978,Competed in Olympic Games,Male,Arvydas Romas•Sabonis,Arvydas•Sabonis,"19 December 1964 in Kaunas, Kaunas (LTU)",NaN,Lithuania Soviet Union,7013.0,223 cm / 122 kg,"Žalgiris Kaunas, Kaunas (LTU) / Real Madrid, M...",Sabas,NaN,"Arvidas Romas Sabonis, Арвидас Ромас Сабонис",Lithuania,NaN,NaN,Arvydas Sabonis,223.0,122.0
5673,Competed in Olympic Games,Male,Gunther•Behnke,Gunther•Behnke,"19 January 1963 in Leverkusen, Nordrhein-Westf...",NaN,Germany,5696.0,221 cm / 114 kg,"TuS Bramsche, Bramsche (GER)",NaN,NaN,NaN,NaN,NaN,NaN,Gunther Behnke,221.0,114.0
7188,Competed in Olympic Games,Male,Vladimir Petrovich•Tkachenko,Vladimir•Tkachenko,"20 September 1957 in Golovinka, Krasnodar Kray...",NaN,Soviet Union,7226.0,220 cm / 110 kg,"BC Budivelnyk, Kyiv (UKR)",Lurch,NaN,NaN,NaN,Владимир Петрович•Ткаченко,NaN,Vladimir Tkachenko,220.0,110.0
6504,Competed in Olympic Games,Male,"Lucien James ""Luc""•Longley",Luc•Longley,"19 January 1969 in Melbourne, Victoria (AUS)",NaN,Australia,6537.0,220 cm / 135 kg,"Phoenix Suns, Phoenix (USA)",NaN,NaN,NaN,NaN,NaN,NaN,Luc Longley,220.0,135.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22298,Competed in Olympic Games,Male,Lajos•Horváth,Lajos•Horváth,"18 March 1872 in Vințu de Jos, Alba (ROU)",NaN,Hungary,22466.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lajos Horváth,NaN,NaN
22301,Competed in Olympic Games,Male,Gyula Sámuel•Iványi,Gyula•Iványi,"10 March 1864 in Budapest, Budapest (HUN)","6 December 1920 in Budapest, Budapest (HUN)",Hungary,22469.0,NaN,"MAC, Budapest (HUN)",NaN,NaN,Gyula von Iványi,NaN,NaN,NaN,Gyula Iványi,NaN,NaN
22302,Competed in Olympic Games,Male,Endre•Kabos (Katz-),Endre•Kabos,"5 November 1906 in Oradea, Bihor (ROU)","4 November 1944 in Budapest, Budapest (HUN)",Hungary,22470.0,NaN,Szolnoki TIVC/Újpesti Torna Egylet,NaN,NaN,NaN,NaN,NaN,NaN,Endre Kabos,NaN,NaN
22304,Competed in Olympic Games,Male,Gusztáv (Gyula)•Kálniczky (Csabuda),Gusztáv•Kálniczky,"17 May 1896 in Budapest, Budapest (HUN)",1964,Hungary,22472.0,NaN,"Honvéd Tiszti Vívó Klub, Budapest (HUN)",NaN,NaN,Gusztáv Kalnitzky,NaN,NaN,NaN,Gusztáv Kálniczky,NaN,NaN
22313,Competed in Olympic Games,Male,Attila•Kovács,Attila•Kovács,"30 December 1939 in Budapest, Budapest (HUN)","10 November 2010 in Budapest, Budapest (HUN)",Hung,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Attila Kovács,NaN,NaN

In [ ]:
# Parse Out Dates from 'Born' and 'Died' Columns
date_pattern = r'(\d \w+ \d{4}|\d{4})'
df['born_date'] = df['Born'].str.extract(date_pattern)
df['born_year'] = df['Born'].str.extract(r'(\d{4})')

df['born_date'] = pd.to_datetime(df['born_date'], errors='coerce')
df['born_year'] = pd.to_numeric(df['born_year'], errors = 'coerce')

df['died_date'] = df['Died'].str.extract(date_pattern)
df['died_date'] = pd.to_datetime(df['died_date'], format="mixed", errors='coerce')

In [ ]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Other names,Nationality,Original name,Name order,name,height_cm,weight_kg,born_date,born_year,died_date
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,1886-12-02,1886.0,1960-10-02
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2.0,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0,1969-04-01,1969.0,NaT
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3.0,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,Jean Borotra,183.0,76.0,1898-08-03,1898.0,1994-07-07
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4.0,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaN,Jacques Brugnon,168.0,64.0,1895-05-01,1895.0,NaT
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5.0,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN,1878-04-07,1878.0,1930-07-05

In [ ]:
# Get city, region and country from Born column
location_pattern = r'in ([\w\s()-]+), ([\w\s-]+) \((\w+)\)'
df['Born'].str.extract(location_pattern)

                 0                     1    2
0         Bordeaux               Gironde  FRA
1           Meulan              Yvelines  FRA
2         Biarritz  Pyrénées-Atlantiques  FRA
3      Paris VIIIe                 Paris  FRA
4       Wandsworth               England  GBR
...            ...                   ...  ...
22309     Budapest              Budapest  HUN
22310     Budapest              Budapest  HUN
22311  Szombathely                   Vas  HUN
22312     Budapest              Budapest  HUN
22313     Budapest              Budapest  HUN

[22314 rows x 3 columns]

In [ ]:
df[['born_city', 'born_region', 'born_country']] = df['Born'].str.extract(location_pattern, expand=True)

In [ ]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Name order,name,height_cm,weight_kg,born_date,born_year,died_date,born_city,born_region,born_country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1.0,NaN,NaN,...,NaN,Jean-François Blanchy,NaN,NaN,1886-12-02,1886.0,1960-10-02,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2.0,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,Arnaud Boetsch,183.0,76.0,1969-04-01,1969.0,NaT,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3.0,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,Jean Borotra,183.0,76.0,1898-08-03,1898.0,1994-07-07,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4.0,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,Jacques Brugnon,168.0,64.0,1895-05-01,1895.0,NaT,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5.0,NaN,"TCP, Paris (FRA)",...,NaN,Albert Canet,NaN,NaN,1878-04-07,1878.0,1930-07-05,Wandsworth,England,GBR

In [ ]:
import pandas as pd

In [ ]:
pd.set_option('display.max_colwidth', None)

df.value_counts('born_city', ascending = False).head(25)

born_city
Budapest                          233
København (Copenhagen)            165
Buenos Aires                      154
Praha (Prague)                    128
Wien (Vienna)                     116
Madrid                             99
Ciudad de México (Mexico City)     96
Montréal                           95
Amsterdam                          88
Toronto                            87
Moskva (Moscow)                    85
Stockholm                          84
Helsinki                           82
Melbourne                          82
London                             78
Barcelona                          77
New York                           72
Montevideo                         72
Berlin                             72
São Paulo                          69
Sydney                             67
Oslo                               66
Bruxelles (Brussels)               64
Roma                               63
Dublin                             58
Name: count, dtype: int64

In [ ]:
# Removing any Unneccasery columns
df.columns

Index(['Roles', 'Sex', 'Full name', 'Used name', 'Born', 'Died', 'NOC',
       'athlete_id', 'Measurements', 'Affiliations', 'Nick/petnames',
       'Title(s)', 'Other names', 'Nationality', 'Original name', 'Name order',
       'name', 'height_cm', 'weight_kg', 'born_date', 'born_year', 'died_date',
       'born_city', 'born_region', 'born_country'],
      dtype='object')

In [ ]:
columns_to_keep = ['athlete_id', 'name', 'born_date', 'born_city', 'born_region',
                   'born_country', 'NOC', 'height_cm', 'weight_kg', 'died_date']

df_clean = df[columns_to_keep]

In [ ]:
df_clean.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1.0,Jean-François Blanchy,1886-12-02,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2.0,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaT
2,3.0,Jean Borotra,1898-08-03,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-07
3,4.0,Jacques Brugnon,1895-05-01,Paris VIIIe,Paris,FRA,France,168.0,64.0,NaT
4,5.0,Albert Canet,1878-04-07,Wandsworth,England,GBR,France,NaN,NaN,1930-07-05